
export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";

export const LODING_DATA = "LODING_DATA";
export const ERROR_HANDLE = "ERROR_HANDLE";

export const GET_FACILITIES = "GET_FACILITIES";
export const ADD_FACILITIES = "ADD_FACILITIES";
export const DELETE_FACILITIES = "DELETE_FACILITIES";
export const Edit_FACILITIES = "Edit_FACILITIES";